import XCTest
import AppKit
import SwiftData
@testable import Yank

private actor PersistenceGate {
    private var snapshots: [PasteboardSnapshot] = []
    private var firstContinuation: CheckedContinuation<Void, Never>?
    private var firstReleased = false

    func persist(_ snapshot: PasteboardSnapshot) async -> ClipboardPersistenceResult {
        snapshots.append(snapshot)
        if snapshots.count == 1 && !firstReleased {
            await withCheckedContinuation { continuation in
                firstContinuation = continuation
            }
        }
        return .saved(prunedCount: 0)
    }

    func releaseFirst() {
        firstReleased = true
        firstContinuation?.resume()
        firstContinuation = nil
    }

    func values() -> [String?] {
        snapshots.map(\.stringValue)
    }
}

@MainActor
final class ClipboardMonitorTests: XCTestCase {
    private func makeContainer() throws -> ModelContainer {
        let config = ModelConfiguration(isStoredInMemoryOnly: true)
        return try ModelContainer(for: ClipItem.self, configurations: config)
    }

    private func writeString(_ value: String, to pasteboard: NSPasteboard) {
        pasteboard.declareTypes([.string], owner: nil)
        XCTAssertTrue(pasteboard.setString(value, forType: .string))
    }

    private func waitForClipboardPoll(description: String = "wait for poll") {
        let expectation = expectation(description: description)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            expectation.fulfill()
        }
        wait(for: [expectation], timeout: 1.0)
    }

    private func waitForPersistenceCount(_ expectedCount: Int, gate: PersistenceGate) async {
        for _ in 0..<100 {
            if await gate.values().count >= expectedCount { return }
            try? await Task.sleep(nanoseconds: 10_000_000)
        }
        XCTFail("Timed out waiting for \(expectedCount) persistence calls")
    }

    // Guards the production default: AppCoordinator constructs ClipboardMonitor
    // without a pasteboard argument, so capture must target .general. No start()
    // call -- this only inspects the injected reference, so it has no side effects.
    func testUsesGeneralPasteboardByDefault() throws {
        let monitor = ClipboardMonitor(modelContainer: try makeContainer())
        XCTAssertTrue(monitor.pasteboard === NSPasteboard.general)
    }

    func testCapturesClipboardChange() throws {
        let container = try makeContainer()
        let pasteboard = makeTestPasteboard()
        let monitor = ClipboardMonitor(modelContainer: container, pasteboard: pasteboard)
        monitor.start()

        addTeardownBlock { monitor.stop() }
        writeString("test capture", to: pasteboard)

        waitForClipboardPoll(description: "clip captured")

        let items = try ModelContext(container).fetch(FetchDescriptor<ClipItem>())
        let captured = items.first(where: { $0.stringValue == "test capture" })
        XCTAssertNotNil(captured)
        XCTAssertEqual(captured?.stringValue, "test capture")
    }

    func testIgnoresSelfPaste() throws {
        let container = try makeContainer()
        let pasteboard = makeTestPasteboard()
        let monitor = ClipboardMonitor(modelContainer: container, pasteboard: pasteboard)
        monitor.start()

        // Simulate PasteService: write with .fromYank marker
        addTeardownBlock { monitor.stop() }
        pasteboard.declareTypes([.string, .fromYank], owner: nil)
        pasteboard.setString("self-pasted content", forType: .string)
        pasteboard.setString("", forType: .fromYank)

        waitForClipboardPoll()

        let items = try ModelContext(container).fetch(FetchDescriptor<ClipItem>())
        let selfPasted = items.first(where: { $0.stringValue == "self-pasted content" })
        XCTAssertNil(selfPasted, "Self-pasted content should not be captured")
    }

    func testIgnoresCaptureSkipMarkers() throws {
        let expectedMarkerRawValues = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType"
        ]
        XCTAssertEqual(
            Set(NSPasteboard.PasteboardType.externalCaptureSkipMarkers.map(\.rawValue)),
            Set(expectedMarkerRawValues)
        )

        for markerRawValue in expectedMarkerRawValues {
            let marker = NSPasteboard.PasteboardType(markerRawValue)
            let container = try makeContainer()
            let pasteboard = makeTestPasteboard()
            let monitor = ClipboardMonitor(modelContainer: container, pasteboard: pasteboard)
            monitor.start()

            defer { monitor.stop() }

            let unmarkedValue = "unmarked content \(marker.rawValue)"
            writeString(unmarkedValue, to: pasteboard)
            waitForClipboardPoll(description: "capture control \(marker.rawValue)")

            var items = try ModelContext(container).fetch(FetchDescriptor<ClipItem>())
            let unmarked = items.first(where: { $0.stringValue == unmarkedValue })
            XCTAssertNotNil(unmarked, "Unmarked content should be captured: \(marker.rawValue)")
            let itemCountAfterUnmarkedCapture = items.count

            pasteboard.clearContents()
            let value = "sensitive content \(marker.rawValue)"
            pasteboard.declareTypes([.string, marker], owner: nil)
            XCTAssertTrue(pasteboard.setString(value, forType: .string))
            XCTAssertTrue(pasteboard.setString("", forType: marker))
            XCTAssertTrue(pasteboard.types?.contains(.string) == true)
            XCTAssertTrue(pasteboard.types?.contains(marker) == true)

            waitForClipboardPoll(description: "skip marker \(marker.rawValue)")

            items = try ModelContext(container).fetch(FetchDescriptor<ClipItem>())
            let captured = items.first(where: { $0.stringValue == value })
            XCTAssertNil(captured, "Marked content should not be captured: \(marker.rawValue)")
            XCTAssertEqual(
                items.count,
                itemCountAfterUnmarkedCapture,
                "Marked content should not add any item: \(marker.rawValue)"
            )
        }
    }

    func testPrunesOldestItemsWhenHistoryLimitIsExceeded() throws {
        let container = try makeContainer()
        let pasteboard = makeTestPasteboard()
        let monitor = ClipboardMonitor(modelContainer: container, pasteboard: pasteboard, historyLimit: 2)
        monitor.start()

        addTeardownBlock { monitor.stop() }

        writeString("oldest item", to: pasteboard)
        waitForClipboardPoll(description: "oldest captured")

        pasteboard.clearContents()
        writeString("middle item", to: pasteboard)
        waitForClipboardPoll(description: "middle captured")

        pasteboard.clearContents()
        writeString("newest item", to: pasteboard)
        waitForClipboardPoll(description: "newest captured")

        let descriptor = FetchDescriptor<ClipItem>(
            sortBy: [SortDescriptor(\ClipItem.createdAt, order: .reverse)]
        )
        let items = try ModelContext(container).fetch(descriptor)
        let values = items.compactMap(\.stringValue)

        XCTAssertEqual(items.count, 2)
        XCTAssertTrue(values.contains("newest item"))
        XCTAssertTrue(values.contains("middle item"))
        XCTAssertFalse(values.contains("oldest item"))
    }

    func testPrunesAllSeededOverflowItemsAfterCapture() throws {
        let container = try makeContainer()
        let seedContext = ModelContext(container)
        let seededDate = Date(timeIntervalSinceNow: -1_000)
        for index in 0..<7 {
            seedContext.insert(ClipItem(
                title: "seed \(index)",
                primaryType: NSPasteboard.PasteboardType.string.rawValue,
                availableTypes: [NSPasteboard.PasteboardType.string.rawValue],
                stringValue: "seed \(index)",
                createdAt: seededDate.addingTimeInterval(TimeInterval(index))
            ))
        }
        try seedContext.save()

        let pasteboard = makeTestPasteboard()
        let monitor = ClipboardMonitor(
            modelContainer: container,
            pasteboard: pasteboard,
            historyLimit: 2
        )
        monitor.start()

        addTeardownBlock { monitor.stop() }
        writeString("trigger item", to: pasteboard)
        waitForClipboardPoll(description: "trigger captured and overflow pruned")

        let descriptor = FetchDescriptor<ClipItem>(
            sortBy: [SortDescriptor(\ClipItem.createdAt, order: .reverse)]
        )
        let items = try ModelContext(container).fetch(descriptor)
        let values = items.compactMap(\.stringValue)

        XCTAssertEqual(items.count, 2)
        XCTAssertTrue(values.contains("trigger item"))
        XCTAssertTrue(values.contains("seed 6"))
        XCTAssertFalse(values.contains("seed 0"))
    }

    func testBusyPollLeavesChangePendingAndRepollsAfterPersistence() async throws {
        let container = try makeContainer()
        let pasteboard = makeTestPasteboard()
        let gate = PersistenceGate()
        let monitor = ClipboardMonitor(
            modelContainer: container,
            pasteboard: pasteboard,
            persistSnapshot: { snapshot in await gate.persist(snapshot) }
        )
        monitor.start()
        addTeardownBlock { monitor.stop() }

        writeString("first", to: pasteboard)
        monitor.pollClipboard()
        await waitForPersistenceCount(1, gate: gate)

        pasteboard.clearContents()
        writeString("second", to: pasteboard)
        monitor.pollClipboard()
        var values = await gate.values()
        XCTAssertEqual(values, ["first"])

        await gate.releaseFirst()
        await waitForPersistenceCount(2, gate: gate)
        values = await gate.values()
        XCTAssertEqual(values, ["first", "second"])
    }
}
