import XCTest
import AppKit
import SwiftData
@testable import Yank

@MainActor
final class ClipboardMonitorTests: XCTestCase {
    private func makeContext() throws -> ModelContext {
        let config = ModelConfiguration(isStoredInMemoryOnly: true)
        let container = try ModelContainer(for: ClipItem.self, configurations: config)
        return ModelContext(container)
    }

    private func writeString(_ value: String, to pasteboard: NSPasteboard) {
        pasteboard.declareTypes([.string], owner: nil)
        XCTAssertTrue(pasteboard.setString(value, forType: .string))
    }

    private func waitForClipboardPoll(description: String = "wait for poll") {
        let expectation = expectation(description: description)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            expectation.fulfill()
        }
        wait(for: [expectation], timeout: 1.0)
    }

    // Guards the production default: AppCoordinator constructs ClipboardMonitor
    // without a pasteboard argument, so capture must target .general. No start()
    // call — this only inspects the injected reference, so it has no side effects.
    func testUsesGeneralPasteboardByDefault() throws {
        let monitor = ClipboardMonitor(modelContext: try makeContext())
        XCTAssertTrue(monitor.pasteboard === NSPasteboard.general)
    }

    func testCapturesClipboardChange() throws {
        let context = try makeContext()
        let pasteboard = makeTestPasteboard()
        let monitor = ClipboardMonitor(modelContext: context, pasteboard: pasteboard)
        monitor.start()

        addTeardownBlock { monitor.stop() }
        writeString("test capture", to: pasteboard)

        waitForClipboardPoll(description: "clip captured")

        let items = try context.fetch(FetchDescriptor<ClipItem>())
        let captured = items.first(where: { $0.stringValue == "test capture" })
        XCTAssertNotNil(captured)
        XCTAssertEqual(captured?.stringValue, "test capture")
    }

    func testIgnoresSelfPaste() throws {
        let context = try makeContext()
        let pasteboard = makeTestPasteboard()
        let monitor = ClipboardMonitor(modelContext: context, pasteboard: pasteboard)
        monitor.start()

        // Simulate PasteService: write with .fromYank marker
        addTeardownBlock { monitor.stop() }
        pasteboard.declareTypes([.string, .fromYank], owner: nil)
        pasteboard.setString("self-pasted content", forType: .string)
        pasteboard.setString("", forType: .fromYank)

        waitForClipboardPoll()

        let items = try context.fetch(FetchDescriptor<ClipItem>())
        let selfPasted = items.first(where: { $0.stringValue == "self-pasted content" })
        XCTAssertNil(selfPasted, "Self-pasted content should not be captured")
    }

    func testIgnoresCaptureSkipMarkers() throws {
        let expectedMarkerRawValues = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType"
        ]
        XCTAssertEqual(
            Set(NSPasteboard.PasteboardType.externalCaptureSkipMarkers.map(\.rawValue)),
            Set(expectedMarkerRawValues)
        )

        for markerRawValue in expectedMarkerRawValues {
            let marker = NSPasteboard.PasteboardType(markerRawValue)
            let context = try makeContext()
            let pasteboard = makeTestPasteboard()
            let monitor = ClipboardMonitor(modelContext: context, pasteboard: pasteboard)
            monitor.start()

            defer { monitor.stop() }

            let unmarkedValue = "unmarked content \(marker.rawValue)"
            writeString(unmarkedValue, to: pasteboard)
            waitForClipboardPoll(description: "capture control \(marker.rawValue)")

            var items = try context.fetch(FetchDescriptor<ClipItem>())
            let unmarked = items.first(where: { $0.stringValue == unmarkedValue })
            XCTAssertNotNil(unmarked, "Unmarked content should be captured: \(marker.rawValue)")
            let itemCountAfterUnmarkedCapture = items.count

            pasteboard.clearContents()
            let value = "sensitive content \(marker.rawValue)"
            pasteboard.declareTypes([.string, marker], owner: nil)
            XCTAssertTrue(pasteboard.setString(value, forType: .string))
            XCTAssertTrue(pasteboard.setString("", forType: marker))
            XCTAssertTrue(pasteboard.types?.contains(.string) == true)
            XCTAssertTrue(pasteboard.types?.contains(marker) == true)

            waitForClipboardPoll(description: "skip marker \(marker.rawValue)")

            items = try context.fetch(FetchDescriptor<ClipItem>())
            let captured = items.first(where: { $0.stringValue == value })
            XCTAssertNil(captured, "Marked content should not be captured: \(marker.rawValue)")
            XCTAssertEqual(
                items.count,
                itemCountAfterUnmarkedCapture,
                "Marked content should not add any item: \(marker.rawValue)"
            )
        }
    }

    func testPrunesOldestItemsWhenHistoryLimitIsExceeded() throws {
        let context = try makeContext()
        let pasteboard = makeTestPasteboard()
        let monitor = ClipboardMonitor(modelContext: context, pasteboard: pasteboard, historyLimit: 2)
        monitor.start()

        addTeardownBlock { monitor.stop() }

        writeString("oldest item", to: pasteboard)
        waitForClipboardPoll(description: "oldest captured")

        pasteboard.clearContents()
        writeString("middle item", to: pasteboard)
        waitForClipboardPoll(description: "middle captured")

        pasteboard.clearContents()
        writeString("newest item", to: pasteboard)
        waitForClipboardPoll(description: "newest captured")

        let descriptor = FetchDescriptor<ClipItem>(
            sortBy: [SortDescriptor(\ClipItem.createdAt, order: .reverse)]
        )
        let items = try context.fetch(descriptor)
        let values = items.compactMap(\.stringValue)

        XCTAssertEqual(items.count, 2)
        XCTAssertTrue(values.contains("newest item"))
        XCTAssertTrue(values.contains("middle item"))
        XCTAssertFalse(values.contains("oldest item"))
    }

    func testPrunesSeededOverflowItemsAcrossBatches() throws {
        let context = try makeContext()
        let seededDate = Date(timeIntervalSinceNow: -1_000)
        for index in 0..<7 {
            context.insert(ClipItem(
                title: "seed \(index)",
                primaryType: NSPasteboard.PasteboardType.string.rawValue,
                availableTypes: [NSPasteboard.PasteboardType.string.rawValue],
                stringValue: "seed \(index)",
                createdAt: seededDate.addingTimeInterval(TimeInterval(index))
            ))
        }
        try context.save()

        let pasteboard = makeTestPasteboard()
        let monitor = ClipboardMonitor(
            modelContext: context,
            pasteboard: pasteboard,
            historyLimit: 2,
            historyPruneBatchSize: 2
        )
        monitor.start()

        addTeardownBlock { monitor.stop() }

        writeString("trigger item", to: pasteboard)
        waitForClipboardPoll(description: "trigger captured")
        waitForClipboardPoll(description: "prune continuations completed")

        let descriptor = FetchDescriptor<ClipItem>(
            sortBy: [SortDescriptor(\ClipItem.createdAt, order: .reverse)]
        )
        let items = try context.fetch(descriptor)
        let values = items.compactMap(\.stringValue)

        XCTAssertEqual(items.count, 2)
        XCTAssertTrue(values.contains("trigger item"))
        XCTAssertTrue(values.contains("seed 6"))
        XCTAssertFalse(values.contains("seed 0"))
    }

    func testPrunesOnlyOneBatchDuringCaptureWhenContinuationIsDelayed() throws {
        let context = try makeContext()
        let seededDate = Date(timeIntervalSinceNow: -1_000)
        for index in 0..<7 {
            context.insert(ClipItem(
                title: "seed \(index)",
                primaryType: NSPasteboard.PasteboardType.string.rawValue,
                availableTypes: [NSPasteboard.PasteboardType.string.rawValue],
                stringValue: "seed \(index)",
                createdAt: seededDate.addingTimeInterval(TimeInterval(index))
            ))
        }
        try context.save()

        let pasteboard = makeTestPasteboard()
        let monitor = ClipboardMonitor(
            modelContext: context,
            pasteboard: pasteboard,
            historyLimit: 2,
            historyPruneBatchSize: 2,
            historyPruneContinuationDelay: 60
        )
        monitor.start()

        addTeardownBlock { monitor.stop() }

        writeString("trigger item", to: pasteboard)
        waitForClipboardPoll(description: "trigger captured")

        let descriptor = FetchDescriptor<ClipItem>(
            sortBy: [SortDescriptor(\ClipItem.createdAt, order: .reverse)]
        )
        let items = try context.fetch(descriptor)
        let values = items.compactMap(\.stringValue)

        XCTAssertEqual(items.count, 6)
        XCTAssertTrue(values.contains("trigger item"))
        XCTAssertTrue(values.contains("seed 6"))
        XCTAssertTrue(values.contains("seed 0"))
        XCTAssertFalse(values.contains("seed 5"))
        XCTAssertFalse(values.contains("seed 4"))
    }
}
