import XCTest
import SwiftData
@testable import Yank

@MainActor
final class ClipboardMonitorTests: XCTestCase {
    private func makeContext() throws -> ModelContext {
        let config = ModelConfiguration(isStoredInMemoryOnly: true)
        let container = try ModelContainer(for: ClipItem.self, configurations: config)
        return ModelContext(container)
    }

    private func waitForClipboardPoll(description: String = "wait for poll") {
        let expectation = expectation(description: description)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            expectation.fulfill()
        }
        wait(for: [expectation], timeout: 1.0)
    }

    func testCapturesClipboardChange() throws {
        let context = try makeContext()
        let monitor = ClipboardMonitor(modelContext: context)
        monitor.start()

        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        addTeardownBlock {
            monitor.stop()
            pasteboard.clearContents()
        }
        pasteboard.setString("test capture", forType: .string)

        waitForClipboardPoll(description: "clip captured")

        let items = try context.fetch(FetchDescriptor<ClipItem>())
        let captured = items.first(where: { $0.stringValue == "test capture" })
        XCTAssertNotNil(captured)
        XCTAssertEqual(captured?.stringValue, "test capture")
    }

    func testIgnoresSelfPaste() throws {
        let context = try makeContext()
        let monitor = ClipboardMonitor(modelContext: context)
        monitor.start()

        // Simulate PasteService: write with .fromYank marker
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        addTeardownBlock {
            monitor.stop()
            pasteboard.clearContents()
        }
        pasteboard.declareTypes([.string, .fromYank], owner: nil)
        pasteboard.setString("self-pasted content", forType: .string)
        pasteboard.setString("", forType: .fromYank)

        waitForClipboardPoll()

        let items = try context.fetch(FetchDescriptor<ClipItem>())
        let selfPasted = items.first(where: { $0.stringValue == "self-pasted content" })
        XCTAssertNil(selfPasted, "Self-pasted content should not be captured")
    }

    func testIgnoresCaptureSkipMarkers() throws {
        let expectedMarkerRawValues = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType"
        ]
        XCTAssertEqual(
            Set(NSPasteboard.PasteboardType.captureSkipMarkers.map(\.rawValue)),
            Set(expectedMarkerRawValues)
        )

        for markerRawValue in expectedMarkerRawValues {
            let marker = NSPasteboard.PasteboardType(markerRawValue)
            let context = try makeContext()
            let monitor = ClipboardMonitor(modelContext: context)
            monitor.start()

            let pasteboard = NSPasteboard.general
            pasteboard.clearContents()
            addTeardownBlock {
                monitor.stop()
                pasteboard.clearContents()
            }

            let unmarkedValue = "unmarked content \(marker.rawValue)"
            XCTAssertTrue(pasteboard.setString(unmarkedValue, forType: .string))
            waitForClipboardPoll(description: "capture control \(marker.rawValue)")

            var items = try context.fetch(FetchDescriptor<ClipItem>())
            let unmarked = items.first(where: { $0.stringValue == unmarkedValue })
            XCTAssertNotNil(unmarked, "Unmarked content should be captured: \(marker.rawValue)")

            pasteboard.clearContents()
            let value = "sensitive content \(marker.rawValue)"
            pasteboard.declareTypes([.string, marker], owner: nil)
            XCTAssertTrue(pasteboard.setString(value, forType: .string))
            XCTAssertTrue(pasteboard.setString("", forType: marker))
            XCTAssertTrue(pasteboard.types?.contains(.string) == true)
            XCTAssertTrue(pasteboard.types?.contains(marker) == true)

            waitForClipboardPoll(description: "skip marker \(marker.rawValue)")

            items = try context.fetch(FetchDescriptor<ClipItem>())
            let captured = items.first(where: { $0.stringValue == value })
            XCTAssertNil(captured, "Marked content should not be captured: \(marker.rawValue)")

            monitor.stop()
            pasteboard.clearContents()
        }
    }
}
