import AppKit

extension NSPasteboard.PasteboardType {
    // Self-paste suppression inspired by Maccy (MIT License, Copyright 2025 Alex Rodionov)
    // https://github.com/p0deje/Maccy
    static let fromYank = NSPasteboard.PasteboardType("com.toku345.Yank.self-paste")

    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    static let externalCaptureSkipMarkers: [NSPasteboard.PasteboardType] = [
        .concealed,
        .transient,
        .autoGenerated
    ]
}
